#!/bin/sh
#intel-drv
xrandr --output HDMI1 --auto --output HDMI2 --left-of HDMI1
#modesetting-drv
xrandr --output HDMI-1 --auto --output HDMI-2 --left-of HDMI-1

#избягване на умрелите редове/колони на EIZO127..
#.config/openbox/rc.xml#margins 
#margin-top е по цялата ширина, затова HDMI2 се премества надолу
#xrandr --output HDMI1 --auto --output HDMI2 --pos 2560x12

# vim:ts=4:sw=4:expandtab
