#!/usr/bin/perl
#############################################################################
# rx_* dispatcher and handlers for VFU File Manager
# (c) Vladi Belperchinov-Shabanski "Cade" 2002  /svd2008
# should live in /usr/lib/vfu/ (absolute path in vfu/vfuarc.cpp). link or remove in src
# usage:
#   rx_* l archive directory   # list archive directory 
#   rx_* v archive             # list entire archive
#   rx_* x archive files...    # extract one file
#   rx_* x archive @listfile   # extract list of files
#
#############################################################################
use strict;

my $CTTL = 16; # cache time to live in seconds

my $file = $ARGV[1];

for( glob "/tmp/*.rx.cache" )
  {
  # clean cache--silently skip errors
  next unless time() - file_mtime( $_ ) > $CTTL;
  unlink $_;
  }

my $rx = choose( $file ) or die "$0: unknown file type, sorry\n";

exec( $rx, @ARGV );

sub choose
{
  local $_ = shift;
  return "rx_tar" if /\.(tar|tar\.(z|gz|bz2)|tz|tgz|tbz)$/i;
  return "rx_zip" if /\.(zip|jar|pk3|egg|maff|odt)$/i;
  return "rx_deb" if /\.deb$/i;
  return "rx_ftp" if /\.ftp$/i;
  return "rx_rar" if /\.rar$/i;
  return "rx_rpm" if /\.rpm$/i;
  return undef;
}

sub file_mtime
{
  return (stat($_[0]))[9];
}

