#!/usr/bin/env python
import sys,os
from util import optz
usage='''
moveLink sourceitem[s] target  -  mv that sees through symlinks
    if target.exists.isdir, move sources inside
    elif target.notexist and one source.isdir, rename it
    elif one source.isfile and target.notexist, rename it
    elif one source.isfile and target.exists(isfile) and --forced, overwrite target
    else error ( multiple sources into inexisting target
              or multiple sources into existing target.file
              or one source.dir into existing target.file )
'''
optz.bool( 'force', '-f', help= 'force source file to overwrite target file if exists'
#    addopt1( 'simvolni',  '-L', help= 'обхожда и символни връзки')

options,args = optz.get()

TODO XXX
