export PYTHONPATH
PYTHONPATH = $(HOME)/src/bin
mn:
	$(PY) radioizv.py rm.izv.yaml  --save
n:
	#echo $$PYTHONPATH
	#python -c 'import sys; print sys.path'
	python3 svd_util/yamls/usability.py rm.izv.yaml
	#python3 svd_util/yamls/usability.py bbb
