#!/bin/bash
cd `dirname $0`
mkdir -p log
exec &>>log/rec.`date +%m%d-%H%M`.$$
date 
./radiorec.py --quiet-mplayer --seconds-extra 200 \
	--exec 'flac --silent {}' \
	--exec '/usr/local/bin/wav44khz.py {}' \
	--exec 'flac --silent {}.44100.wav' \
	"$@" 

#	--exec 'lame --quiet --nohist -h -v -V 6 {}' \
#	--exec 'lame --quiet --nohist -h -v -V 6 {}.44100.wav' \
#
