#!/bin/bash
cd `dirname $0`
mkdir -p log
exec &>>log/rec.`date +%m%d-%H%M`.$$
date 
echo "$@"
./radiorec.py --quiet --extra-seconds 100 \
	--exec '/usr/bin/sync {}' \
	--exec '/usr/local/bin/wavres44khz.py {} -t flac' \
	--exec '/usr/local/bin/wavdel.py --rm {}' \
	"$@" &


exec &>>log/rec.`date +%m%d-%H%M`.$$-2
date 
echo "$@"
./radiorec.py --quiet --extra-seconds 100 \
	--stream2 'http://stream.bnr.bg:8003/botev.mp3' \
	--exec '/usr/bin/sync {}' \
	--exec '/usr/local/bin/wavres44khz.py {} -t flac' \
	--exec '/usr/local/bin/wavdel.py --rm {}' \
	"$@" &

exec &>>log/rec.`date +%m%d-%H%M`.$$-3
date 
echo "$@"
./radiorec.py --quiet --extra-seconds 100 \
	--recorder "/usr/local/bin/softfm -f 104800000 -r 44100 -q -W {ofname}" \
	--exec '/usr/bin/sync {}' \
	--exec '/usr/local/bin/wavres44khz.py {} -t flac' \
	--exec '/usr/local/bin/wavdel.py --rm {}' \
	"$@" &

#	--exec 'flac --silent {}' \
#	--exec '/usr/local/bin/wav44khz.py {}' \
#	--exec 'flac --silent {}.44100.wav' \

#	--exec 'lame --quiet --nohist -h -v -V 6 {}' \
#	--exec 'lame --quiet --nohist -h -v -V 6 {}.44100.wav' \
#
