#!/bin/bash
cd `dirname $0`
mkdir -p plan in
exec &>>radioschedule.log
date 
./radioschedule.py --oenc=utf-8 --days=2 \
	--cron="`pwd`/radiorec --retry_delay_seconds=25 --retry_n=12" \
	--cron-fname-notime \
	--cron-earlier-minutes=5 \
	--cron-later-minutes=2 \
	--cron-later-percent=20 \
	--save-plan=plan/p \
	--save-input=in/i \
	--nalichni-opisi='/home/svilen/azcom/detski/zvuk/*/op/*' \
	--nalichni-vremena="`pwd`/vremena" \
	--force=hb-6:50-7:00!/1:5-събуди_ме_с_пр \
 	--force=hb-19:20-19:30/1:5-време_за_пр \
 	--force=hb-21:20-21:30/1:5-ркц \
 	--force=hb-16:00-17:00/7-рт \
	--channel=hristobotev "$@" \
		>radiorec-crontab && crontab -u svilen radiorec-crontab

##	--channel=horizont \
##	--channel=varna \
##

NOSUDO=1 /home/svilen/bin/nfsrights .

#	--force=hb-08:10-08:40/6:7-ртдц \
# 	--force=hb-00:15-01:55/1:5,7-ртз \
# 	--force=hb-22:25-22:27-proba \
#	--save-text \
#	--channel=sofia 
