#!/bin/bash
#while [[ "$1" =~ ^- ]] ; do
while true ; do
  case "$1" in 
    --len=[1-9]*)   LEN="${1#--len=}" && shift ;;
    -l=[1-9]*)      LEN="${1#--len=}" && shift ;;
    --nobeg)        NOBEG=1 && shift ;;
    --noend)        NOEND=1 && shift ;;
    *)  break ;;
  esac  
done

L=${LEN:-3}
test -z "$NOBEG" && BEG=0
test -z "$NOEND" && END=-$L
#END=1
echo "len=$L beg=$BEG end=$END ofs=$OFS"

for f in "$@"; do
    for a in $BEG $END ; do 
        case $a in
         -*) a=`filmid0.sh "$f" | perl -ne 'print if s/ID_LENGTH=//'`$a ;;
        esac
        #-ss = start
        #-endpos = length
        $E mplayer -ss `echo $a+${OFS:-0} | bc` -endpos $L "$f" 
        done
done 
# vim:ts=4:sw=4:expandtab
