#!/bin/bash
enco() {
    a="$1"
    echo 'xxx' $a $oSIZE
    test -e "$a" || return
    if [ -f "$a" ]; then
        echo "$a" | grep -iE '\.(avi|iso|m2ts|ts|mkv|mp4|mov|mpg|mpeg|wmv|flv|fli|asf|m4v|webm)$' || return
    fi

    for TITLE in `test -f "$a".izbor && cat "$a".izbor || echo "z"`; do 
     echo "============================ $oSIZE $a $TITLE"
     test "$TITLE" = 'z' || export TITLE
     $E menc2hb "$a"
     echo aree
     #"$a".mkv
    done
    unset TITLE
    #echo "============================ $a"
    #$E menc2hb "$a" "$a".mkv
    #test -f "$a".mkv* && 
    mkdir -p ok/ && /bin/mv -f "$a"* ok/
}


shopt -s nullglob

while true; do
# rename.pl 's/(\.\w{2,4})$/\L$1/' todo/w/*/* todo/* 
# if a file is missed, probably it is unreadable/permissions
 for a in todo/w/*/* ; do
    echo $a
    W=`echo $a|perl -ne 's,^todo/w/(\d+)/.*,\1,; print'`
    export oSIZE="-w $W"
    enco "$a"
 done
 for a in todo/* ; do
    test "$a" = "todo/w" && continue
    test "$a" = "todo/ne" && continue
    echo $a
    unset oSIZE
    enco "$a"
 done
 echo waiting
 sleep ${SLEEP:-20}
done
# vim:ts=4:sw=4:expandtab
