#!/bin/sh
if test -z "$NOTITLE"; then 
if test -z "$TITLE"; then WHAT="--main-feature"; else WHAT="-t $TITLE" ; fi
fi
oVIDEO="--vfr"
#oQUALITY="-vb 2000"
oQUALITY="-q ${QUALITY:-20}"
test -n "$P720" && oSIZE="-w 1280"
oLANG="--native-language bul --native-dub"
I="$1"
shift
O="$2"
case "x$O" in
 x-*|x) O="$I" ;; 
 x*) shift ;;
esac 
O="$O.$TITLE"
echo -- args: -e x264 -2 -T $oVIDEO $oQUALITY $oSIZE $oLANG $WHAT -i "$I" -o "$O.mkv" "$@"
$E handbrake-cli -e x264 -2 -T $oVIDEO $oQUALITY $oSIZE $oLANG $WHAT -i "$I" -o "$O.mkv" "$@"
