#!/bin/sh
if test -z "$NOTITLE"; then 
if test -z "$TITLE"; then WHAT="--main-feature"; else WHAT="-t $TITLE" ; fi
fi
oAUDIO="--aencoder copy  --audio-copy-mask aac,ac3,mp3  --audio-fallback ffac3"
oVIDEO="--vfr"
#oQUALITY="-vb 2000"
oQUALITY="-q ${QUALITY:-20}"
test -n "$P720" && oSIZE="-w 1280"
oLANG="--native-language bul --native-dub"
I="$1"
shift
O="$2"
case "x$O" in
 x-*|x) O="$I" ;; 
 x*) shift ;;
esac 
xSIZE=`perl -e '$_=$ENV{oSIZE}; s/[ -]//g; print'`
O="$O.$TITLE.$xSIZE".mkv
       
echo    -- args: -e x264 -2 -T $oVIDEO $oAUDIO $oQUALITY $oSIZE $oLANG $WHAT -i "$I" -o "$O" "$@"
$E handbrake-cli -e x264 -2 -T $oVIDEO $oAUDIO $oQUALITY $oSIZE $oLANG $WHAT -i "$I" -o "$O" "$@"
