#$Id$
now:
	python colorvcs.py svn < test-svn
	python colorvcs.py cvs < test-cvs
	python colorvcs.py bzrupd  < test-bzrupd
	python colorvcs.py bzrstat < test-bzrstat
	python colorvcs.py bzr     < test-bzrupd
	python colorvcs.py bzr     < test-bzrstat
# vim:ts=4:sw=4:noexpandtab
