#!/bin/sh
#echo "$9" && exit
app="$1"
shift

ff="$1"
f=`basename "$1"`
shift

echo -n "$f\r"
test -n "$FIND" && ff=`find $DIR -name "$f"`
test -z "$ff" && exit
echo "$ff                  " 
if test -z "$REMOVEALL"; then 
 "$app" "$@" "$ff" 
else
 "$app" "--remove-all" "$ff" 
fi
