#!/bin/sh
TARGET="$1"
shift
COMMENT="$1"
shift
echo comment:"$COMMENT"
mp3info -c "$COMMENT" "$@"
mp3wrap "$TARGET".mp3 "$@"
mp3info -c "$COMMENT" "$TARGET"_MP3WRAP.mp3
mp3info "$TARGET"_MP3WRAP.mp3 "$@"
