a: k #z


#Z=/home/tmp/Zamunda.NET.html
z:
	./hf.py --iz zamunda --skri mahni-filmi.txt $Z > zz.html
	ln -f zz.html /home/tmp/

STR ?= 6
S ?= $(STR)
#K=kinozal.html
k:
	./hf.py --iz kinozal --skri mahni-filmi.txt $(if $S,--str=$S) $K >kk.html
	ln -f kk.html /home/tmp/

# vim:ts=4:sw=4:noexpandtab
