#!/bin/sh
X=${1:-locale}
PFX=$2
SFX=$3
echo "$X" --$PFX-- --$SFX--
# !(bg|en)
sudo rm -rf "$X"/${PFX}[acdf-z]*$SFX
sudo rm -rf "$X"/${PFX}b[a-fh-z]*$SFX
sudo rm -rf "$X"/${PFX}e[a-mo-z]*$SFX
sudo rm -rf "$X"/${PFX}en_[A-TV-Z]*$SFX
sudo rm -rf "$X"/${PFX}en@*$SFX
