#!/bin/sh
X=${1:-locale}
X=${X%/}
PFX=$2
SFX=$3
PFX2=${4:-$PFX}
test "$SFX" = "/" && _R=-r
#E=echo
echo "$X" --$PFX-- --$SFX-- --$PFX2--
for d in "$X"/ ; do (
 test -d "$d" && cd "$d" && sudo $E rm -f $_R ` ls -1d ${PFX}*$SFX 2>/dev/null | grep -Ev "^$PFX2(bg|en|us|en[_-]US|en[_-]GB|i18n|iso14651_t1(_common|$)|translit)" `
 )
done

# vim:ts=4:sw=4:expandtab
