#!/bin/sh
#set -x
rm='sudo rm -rf'
rmfind() { sudo find $1 -name "$2" -delete ; }

# path PFX SFX PFX2
dellocale /usr/share/locale/ "" /
$rm /usr/share/locale/en{_CA,_GB,@*}
dellocale /usr/share/i18n/locales/
dellocale /usr/share/kbd/locale/
dellocale /usr/lib/chromium/locales/
dellocale /usr/lib/opera/localization/
dellocale /usr/share/lxpanel/images/xkb-flags/ '' .png
dellocale /usr/share/libexttextcat/ '' .lm
dellocale /usr/share/gnupg/ help. .txt
$rm /usr/share/owncloud/i18n/
dellocale /usr/share/gitk/lib/msgs/
dellocale /usr/share/git-gui/lib/msgs/

dellocale /usr/share/tuxpaint/locale/ '' .ttf
dellocale /usr/share/tuxpaint/locale/ '' _docs
$rm /usr/share/tuxpaint/fonts/locale/
find /usr/share/tuxpaint/ -type d -exec dellocale {} '*_desc_' .ogg '.*_' \;

$rm /usr/share/etr/music/{freez,calm,spun,start1,options1}*.ogg


P=/usr/bin/
$rm $P/gtk*demo* $P/demo*gtk* $P/x264
$rm /usr/share/gtk*-doc

#openmotif
$rm /usr/share/Xm
$rm /usr/share/man/man3/Xm*

#libguile needed by make.. del the rest
$rm /usr/share/guile
#$rm /usr/lib/guile/*/ccache
$rm /usr/lib/guile/ /usr/share/guile/ /usr/include/guile/
$rm /usr/share/info/guile* /usr/share/info/r5rs.info.gz

P=/usr/lib/libreoffice/
$rm $P/program/wizards/
$rm $P/share/gallery/*/
$rm $P/share/template/common/layout/
$rm $P/share/template/common/wizard/
$rm $P/share/template/wizard/
$rm $P/LICENSE* $P/CREDIT*
$rm $P/share/config/images_hicontrast.zip
$rm $P/help
$rm $P/sdk/

P=/usr/lib/python*/
$rm $P/test/ $P/idle*/ $P/tkinter/
$rm $P/*/test/ $P/*/tests/
$rm $P/site-packages/*/test/
$rm $P/site-packages/*/tests/
$rm $P/site-packages/*/*/tests/
$rm $P/site-packages/*/*/*/tests/
$rm $P/site-packages/*/*/*/*/tests/
$rm $P/site-packages/*/SelfTest/
#$rm $P/site-packages/bzrlib/plugins/*/test*
#$rm $P/site-packages/numpy/*/tests
$rm $P/site-packages/mercurial/locale/*
$rm $P/site-packages/pygame/examples
$rm $P/site-packages/pygame/docs

P=/usr/share/doc
$rm $P/python*/html/_sources/
$rm $P/python*/html/{gen,search}index*

$rm $P/[a-oq-zA-Z0-9]*
$rm $P/p[a-xzA-Z0-9]*
$rm $P/python-* $P/python?-*

V=/usr/share/vim/vim*/
$rm $V/tutor $V/lang
$rm $V/spell/*latin*
$rm $V/doc/versio*
$rm $V/syntax/{xs,*muttrc,pfmain,baan,redif,foxpro,autoit}.vim
$rm $V/autoload/phpcomplete.vim


P=/usr/lib/qt4/bin/
$rm $P/??c $P/assistant $P/l* $P/designer $P/qdoc*
$rm /usr/share/qt4/translations/

dellocale /usr/share/skype/lang/ skype_

dellocale /usr/share/opera/locale/
#$rm [acdf-z]* b[a-fh-z] e[a-mo-z]
$rm /usr/share/xml/docbook/xsl-stylesheets-*/common/{zh,sr,pt,bn}_*

P=/usr/share/icons/
$rm $P/*/{512x,384x,256x,scalable}*

$rm /usr/share/licenses/
$rm /usr/share/liblouis

$rm /usr/share/ghostscript/*/doc/
$rm /usr/share/ghostscript/*/examples/

$rm /usr/share/GeoIP/*v6*
$rm /usr/share/fonts/OTF/

P=/usr/share/man/man3
$rm $P/*.3perl.*
rmfind $P '*.3p[mn].*'
rmfind $P '*.3ssl.*' 
$rm $P/{ASN,CURL,DSA,Fc,SDL,SSL,Tcl}*
$rm $P/*_sp.*
$rm $P/Xkb*
$rm $P/X{t,curs,cms,db,mb,rm,au,ine,utf,v,wc}*
#$rm $P/X{Add,Create,Change,Draw,Allo,Free,Shap,Screen}*
$rm $P/X[A-Z]*
$rm $P/__gnu_*
$rm $P/SVN*
$rm $P/TIFF*
$rm $P/{ber_,fribidi_,gnutls,ldap_,ldns_,libssh}*
$rm $P/{pam,pcap,pcre,sd_,sem_}*
$rm $P/{slk,udev,xdr_}*
rmfind $P 'xcb*'
$rm $P/pipe[cl]* $P/secc*
$rm $P/set_* $P/zip_*
$rm $P/SD_* $P/SLIST* $P/LIST* $P/STAIL* $P/TAIL*
$rm $P/{aa,acl,af,aio,archive,asn1,cap,clnt,curl,curs,dane,el_,field_,form_}*
$rm $P/{idn,item_,keyctl,libcurl,ne_,opus_,rpc_,svc,tld_,tok_}*
$rm $P/{CIRC,CMSG,CPU_,DMX,DPMS,Default,RB,SPI,SPLAY,TYPE_}*

P=/usr/share/man
$rm $P/[acdf-ln-z]* $P/b[a-fh-z].* $P/e[a-mo-z].* $P/b[a-fh-z] $P/e[a-mo-z]
$rm $P/man1/perl*delta*

$rm /usr/share/perl5/core_perl/pod/
$rm /usr/bin/core_perl/pod*
$rm /usr/*bin/pod2*


#mesa-demos
$rm /usr/bin/osdemo*
$rm /usr/sbin/osd_login

P=/usr/lib/modules/*/kernel/drivers
$rm $P/staging/ #{lustre,comedi,speakup}
$rm $P/{isdn,infiniband}
## $rm $P/media/dvb-*
# $rm $P/media/tuners
# $rm $P/media/pci/{bt8,ttpci,saa,cx,ivtv}*
# #$rm $P/media/usb/{gspca,dvb*,cx*,em*,tm*,go7007}
$rm $P/scsi/{aic*,bnx*,megaraid,mpt3*,lpfc,bfa,qla*}
$rm $P/gpu/drm/{radeon,amd*}
$rm $P/net/ethernet/{mellanox,qlogic,chelsio,sfc,cavium,dec,sun,netronome}

P=/usr/lib/firmware
$rm $P/{ti-connectivity,liquidio,netronome,mellanox,qlogic}
$rm $P/{amdgpu,radeon}
$rm $P/bnx2*
$rm $P/{mrvl,ar3k,slicoss,go7007,emi*,qca}
$rm $P/{libertas,carl9170fw,mwl*,moxa,vxge,qed,cxgb4,ueagle-atm}
$rm $P/{myri*,phan*,ct*fw*,qat*,cbfw*,s5*} #iwlwifi*=intel  i2400*,i6050*=?
# $rm $P/{brcm,radeon,amdgpu}

P=/usr/lib*/dri
$rm $P/r* $P/nouv* $P/zink*

$rm /usr/share/help/*

P=/usr/include
#SDL*
for a in `cat <<HHHHHHHH
gtk* 
CLucene
GL
ImageMagick
claws-mail libetpan
epoxy
gimp
glib
gstreamer
krb
mozjs- js-
ntfs
openssl
php
poppler
postgresql
mysql
qt
subversion
xercesc
wine
wx-
HHHHHHHH
`; do $rm $P/$a*; done

P=/usr/lib
$rm $P/libmupdf.a
$rm $P/libLL*.a
$rm $P/libeca*.a
$rm $P/libruby*.a
$rm $P/libQt*.a

$rm /usr/share/sip

P=/usr/share/terminfo
$rm $P/w
$rm $P/d/d[0-9]*
$rm $P/a/att*
$rm $P/n/ncr*
$rm $P/t/tvi*

P=/usr/share/liblouis/tables/
$rm $P/*{hu,ko,de,zh,pl,fr,Fr,cs,sv,it,gr,pt,no,nl,da}[-_]*

P=/usr/share/SFML/
$rm $P/doc
$rm $P/examples

P=/usr/share/gimp/*/
$rm $P/dynamics/
$rm $P/tips
$rm $P/patterns
$rm $P/gimpressionist
$rm $P/brushes/{Texture,Media,Splatters,*obsolet*}


$rm /var/log/journal/*/system@*
$rm /var/log/journal/*/user-*@*

#$rm /usr/share/gir-1.0 /usr/share/gir-1.0--
#$rm /usr/lib/girepository-*

P=/usr/share/info
$rm $P/{as,bfd,gcc,gdb,gawk,gsl,auto[cm],gettext,bison,flex,xorriso,texinfo,gnutls,tar,aspell,ld,lib}*

$rm /usr/share/jack-audio-connection-kit/reference/html
#$rm /usr/share/graphviz/doc/ #{html,ChangeLog,COPYING}

#$rm /usr/bin/smbtorture /usr/bin/php

$rm /usr/share/ibus/*
